services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample-db
    ports:
      - "5432:5432"
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spring-boot-kotlin-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sample-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    image: spring-boot-kotlin-sample:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
